repository:
  name: datatogether-superset
  description: Heroku-backed Superset instance for visualizing live project data.
  homepage: https://datatogether-superset.herokuapp.com
  default_branch: master
